import { Platform } from "react-native";
import images from "../../assets/images";
import { OnboardingSlide } from "../../types/onboarding";

export const DEVICE_TYPE = 'gpi_app';
export const IS_IOS = Platform.OS === 'ios';
export const IS_ANDROID = Platform.OS === 'android';

export const onboardingData: OnboardingSlide[] = [
    {
        id: '1',
        title: 'Stay Informed, Anytime',
        description: 'Get instant access to the latest updates, stories, and news highlights — wherever you are.',
        image: images.onboarding1,
    },
    {
        id: '2',
        title: 'Tailor Your News Feed',
        description: 'Follow topics you care about and discover trusted sources that match your interests.',
        image: images.onboarding1,
    },
    {
        id: '3',
        title: 'Read It When You Want',
        description: 'Save your favorite articles and catch up later, at your own pace.',
        image: images.onboarding1,
    },
];

export const STRINGS = {
    //Error Messages
    INTERNAL_ERROR: 'InternalError',
    TRY_AFTER_SOME_TIME: 'TryAfterSomeTime',
    SIGN_IN_ERROR_TITLE: 'Error',
    SIGN_IN_ERROR: 'Sign In Error',
    EMAIL_ALREADY_EXISTS: 'EmailAlreadyExist',

    // Validation Error Messages
    FIRST_NAME_REQUIRED: 'RequireFirstName',
    LAST_NAME_REQUIRED: 'RequireLastName',
    EMAIL_REQUIRED: 'RequireEmail',
    EMAIL_INVALID: 'EmailInvalid',
    COUNTRY_REQUIRED: 'RequireCountry',
    GENDER_REQUIRED: 'RequireGender',
    TERMS_REQUIRED: 'TermsRequired',
    ALL_FIELDS_REQUIRED: 'All Fields Required',

    // Verification
    VERIFICATION_CODE: "VerficationCode",
    VERIFICATION_CODE_DESCRIPTION: "EnterVerificationCodeSentByEmail",

    // Account & Authentication
    I_AGREE_TO_THE_TERMS_AND_CONDITIONS: 'NoMarketingEmail',
    SKIP: 'Skip',
    NEXT: 'Next',
    SIGN_IN: 'SignIn',
    SIGN_UP: 'SignUp',
    EMAIL: 'Email',
    FIRST_NAME: 'FirstName',
    LAST_NAME: 'LastName',
    COUNTRY: 'Country',
    GENDER: 'Gender',
    EMAIL_PLACEHOLDER: 'user@example.com',
    COUNTRY_PLACEHOLDER: 'Select a country',
    GENDER_PLACEHOLDER: 'Select gender',
    ALREADY_HAVE_AN_ACCOUNT: 'AlreadyHaveAnAccount',
    NOT_A_MEMBER_YET: 'NotMemberYet',
    CONTINUE_WITHOUT_SIGNING_IN: 'ContinueWithoutSigningIn',
    PLEASE_SIGN_IN_TO_YOUR_ACCOUNT: 'PleaseSignIntoYourAccount',
    CREATE_YOUR_ACCOUNT: 'CreateAccount',
    CREATE_YOUR_ACCOUNT_DESCRIPTION: 'WelcomeIntoYourAccount',
    SIGN_IN_ERROR_MESSAGE: 'Please fill in all fields',
    SIGN_IN_ERROR_BUTTON: 'OK',
    SIGN_OUT_TITLE: 'Sign Out',
    SIGN_OUT_DESCRIPTION: 'Are you sure you want to sign out?',
    SIGN_OUT_BUTTON: 'Sign Out',
    CANCEL: 'Cancel',

    // New strings from JSON
    ABOUT: 'About',
    ACCEPT: 'Accept',
    ACCESS_BELOW_CONTENT: 'AccessBelowContent',
    ACCOUNT: 'Account',
    ACCOUNT_DELETED: 'AccountDeleted',
    ACCOUNT_SUCCESSFULLY_DELETED: 'AccountSuccessFullyDeleted',
    ADD_TO_YOUR_SELECTIONS: 'AddToYourSelections',
    ALERT: 'Alert',
    ALREADY_A_SUBSCRIBER: 'AlreadyASubscriber',
    ALREADY_SUBSCRIBED: 'AlreadySubscribed',
    APPEARANCE: 'Appearance',
    APPEARANCE_SUMMARY: 'AppearanceSummary',
    APPLICATION_SETTINGS: 'ApplicationSettings',
    APP_NOT_LOAD: 'AppNotLoad',
    BILLING: 'Billing',
    CHECK_EMAIL: 'ChechEmail',
    CHOOSE_PLAN: 'ChoosePlan',
    CONTENT_NOT_AVAILABLE: 'ContentNotAvailable',
    CONTINUE_AS_GUEST: 'ContinueAsGuest',
    CREATE_NEW_ACCOUNT: 'CreateNewAccount',
    CUSTOMIZE_FONT_SIZE: 'CustomizeFontSize',
    DATA_RETRIEVE_ERROR: 'DataRetriveError',
    DELETE_ACCOUNT: 'DeleteAccount',
    DELETE_ACCOUNT_DESC_1: 'DeleteAccountDesc1',
    DELETE_ACCOUNT_DESC_2: 'DeleteAccountDesc2',
    DESC_NOT_AVAILABLE: 'DescNotAvailable',
    DISABLED: 'Disabled',
    DISABLED_DESC: 'DisabledDesc',
    DISABLED_DESC_FOR_PHOTOS: 'DisabledDescForPhotos',
    DONE: 'Done',
    EMAIL_NOT_EXIST: 'EmailNotExist',
    ENABLED: 'Enabled',
    ENTER_VALID_EMAIL: 'EnterValidEmail',
    ENTER_VALID_OTP: 'EnterValidOtp',
    ERROR: 'Error',
    ERROR_ADD_SELECTION: 'ErrorAddSelection',
    ERROR_FETCHING_FAV_DATA: 'ErrorFechingFavData',
    ERROR_GETTING_PROFILE_DATA: 'ErrorGettingProfileData',
    ERROR_LOAD_LANGUAGE: 'ErrorLoadLanguage',
    ERROR_REGISTER_DEVICE_FOR_NOTIFICATION: 'ErrorRegisterDeviceForNotification',
    ERROR_REMOVE_SELECTION: 'ErrorRemoveSelection',
    ERROR_WHILE_GETTING_PROFILE: 'ErrorWhileGettingProfile',
    ERROR_WHILE_UPGRADING: 'ErrorWhileUpgrading',
    ESSENTIAL: 'Essential',
    FAILED_REQUEST_RETRIEVAL_ARTICLE: 'FailedRequestRetrievalArticle',
    FAV_NOT_FOUND: 'FavNotFound',
    FEATURES: 'Features',
    FEMALE: 'Female',
    FONT_SIZE: 'FontSize',
    FONT_SIZE_SUMMARY: 'FontSizeSummary',
    FREE: 'Free',
    FULL_ACCESS: 'FullAccess',
    GENERAL_TERMS_AND_PRIVACY: 'GeneralTermsAndPrivacy',
    GO_BACK_AND_TRY: 'GoBackAndTry',
    GPI_ABO: 'GPIABO',
    INVALID_EMAIL_AND_PASS: 'InvalidEmailAndPass',
    KEEP_DEVICE_SETTING: 'KeepDeviceSetting',
    LANGUAGE: 'Language',
    LENGTH_GREATER_2: 'LengthGreter2',
    LET_SIGN_IN: 'LetSignIn',
    LIMITED: 'Limited',
    LOGIN: 'Login',
    LOGIN_FIRST: 'LoginFirst',
    LOGIN_FIRST_FOR_SUBSCRIBE: 'LoginFirstForSubscribe',
    LOGIN_OR_REGISTER_TO_LINK: 'LoginOrRegisterToLink',
    LOGIN_OR_REGISTER_TO_LINK_SUBSCRIPTION: 'LoginOrRegisterToLinkSubscripion',
    LOGIN_SUCCESS: 'LoginSuccess',
    LOGIN_TO_ADD_TO_YOUR_SELECTION: 'LoginToAddToYourSelection',
    LOG_OUT: 'LogOut',
    LOG_OUT_CONFIRMATION: 'LogOutConfirmation',
    LOGOUT_SUCCESS: 'LogoutSuccess',
    MAGIC_LINK_SENT: 'MagicLinkSent',
    MAGIC_LINK_EXPIRE: 'MaginLinkExpire',
    MALE: 'Male',
    MANAGE_SUBSCRIPTION: 'ManageSubscription',
    MANAGE_YOUR_SUBSCRIPTION: 'ManageYourSubscription',
    MONTHLY: 'Monthly',
    NEW_FEATURES_AVAILABLE: 'NewFeaturesAvailable',
    NEW_UPDATE_AVAILABLE: 'NewUpdateAvailable',
    NO_ACCESS: 'NoAccess',
    NO_DATA: 'NoData',
    NON_SUBSCRIBER: 'NonSubscriber',
    NO_SUBSCRIPTION_FOUND: 'NoSubscriptionFound',
    NOTIFICATIONS: 'Notifications',
    NOTIFICATIONS_DISABLED: 'NotificationsDisabled',
    NOT_LOADED_DESC: 'NotLoadedDesc',
    NOT_MATCH: 'NotMatch',
    NOT_RECEIVE_OTP: 'NotReceiveOtp',
    OK: 'Ok',
    ON_BOARDING_HEADING_1: 'OnBoardingHeading1',
    ON_BOARDING_HEADING_2: 'OnBoardingHeading2',
    ON_BOARDING_HEADING_3: 'OnBoardingHeading3',
    ON_BOARDING_TEXT_1: 'OnBoardingText1',
    ON_BOARDING_TEXT_2: 'OnBoardingText2',
    ON_BOARDING_TEXT_3: 'OnBoardingText3',
    OR: 'OR',
    OTP_SEND_SUCCESS: 'OtpSendSuccess',
    PREMIUM: 'Permium',
    PHONE: 'Phone',
    PHOTOS: 'Photos',
    PHOTOS_ACCESS_DENIED: 'PhotosAccessDenied',
    PLAN_DESC_1: 'PlanDesc1',
    PLAN_DESC_2: 'PlanDesc2',
    PLAN_DESC_3: 'PlanDesc3',
    PLAN_DESC_4: 'PlanDesc4',
    PLEASE_LOGIN: 'PleaseLogin',
    PLEASE_LOGOUT_CURR_ACC_AND: 'PleaseLogoutCurrAccAnd',
    PLEASE_WAIT: 'PleaseWait',
    PREVIEW_FONT_SIZE: 'PreViewFontSize',
    PREVIEW_FONT_SIZE_DESC: 'PreviewFontSizeDesc',
    PROFILE: 'Profile',
    PURCHASE_SUCCESS: 'PurchaseSuccess',
    REGISTER_FOR_FREE: 'RegisterForFree',
    REGISTER_WITH_ANOTHER_MAIL: 'RegisterWithAnotherMail',
    REMIND_ME_LATER: 'RemindMeLater',
    REOPEN_APP_WHILE_STABLE_CONNECTION: 'ReopenAppWhileStableConnection',
    REQUIRE_OTP: 'RequireOTP',
    RESEND: 'Resend',
    RESEND_IN: 'ResendIn',
    RESET: 'Reset',
    RESTORE_AGAIN: 'RestoreAgain',
    RESTORE_SUBSCRIPTION: 'RestoreSubscription',
    RETRIEVAL_UNSUCCESSFUL: 'RetrievalUnsuccessful',
    RETRY: 'Retry',
    SECONDS: 'Seconds',
    SECTION_CUSTOMIZATION: 'SectionCustomization',
    SECTION_CUSTOMIZATION_SUMMARY: 'SectionCustomizationSummary',
    SECTION_NOT_LOAD: 'SectionNotLoad',
    SECTION_NOT_LOAD_DESC: 'SectionNotLoadDesc',
    SECTIONS: 'Sections',
    SELECT_LANGUAGE: 'SelectLanguage',
    SELECT_LANGUAGE_DESC: 'SelectLanguageDesc',
    SETTINGS: 'Settings',
    START_DATE: 'StartDate',
    SUBMIT: 'Submit',
    SUBSCRIBE: 'Subscribe',
    SUBSCRIBER: 'Subscriber',
    SUBSCRIPTION: 'Subscription',
    SUBSCRIPTION_ON_GPI: 'SubscriptionOnGPI',
    SUCCESS: 'Success',
    SUCCESSFULLY_ADDED: 'SuccessfullyAdded',
    SUCCESSFULLY_REMOVED: 'SuccessfullyRemoved',
    TERMS_AND_PRIVACY: 'TermsAndPrivacy',
    TEXT_SIZE: 'TextSize',
    THANK_YOU_FOR_SUBSCRIBE: 'ThnakYouForSubscribe',
    THROUGH: 'Through',
    TO_ACCESS_PREMIUM_CONTENT: 'ToAccessPremiumContent',
    TO_READ_MORE: 'ToReadMore',
    TO_WATCH_VIDEO: 'ToWatchVdo',
    TRANSACTION_ID: 'TransactionID',
    UPDATE_NOW: 'UpdateNow',
    UPGRADE_CANCELLED: 'UpgradeCancelled',
    VERSION: 'Version',
    VERSION_NO_LONGER_SUPPORTED: 'VersionNoLongerSupported',
    VIDEO_NOT_AVAILABLE: 'VideoNotAvailable',
    VIDEOS_NOT_YET_AVAILABLE: 'VideosNotYetAvailable',
    YOUR_SUBSCRIPTION_IS_LIMITED: 'YourSubscriptionIsLimited',
    YEARLY: 'Yearly',
}